[package]
name = "rust_project_2020"
version = "0.0.1"
authors = ["Rijk van Putten"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.33"

[[bin]]
name = "hello_world"
path = "src/main.rs"

[[bin]]
name = "demo"
path = "src/demo.rs"

[[bin]]
name = "demo2"
path = "src/demo2.rs"

[[bin]]
name = "game"
path = "src/game.rs"

[[bin]]
name = "gfx-demo"
path = "src/gfx-demo.rs"