name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Packages
      run: sudo apt-get update
    - name: Install some packages to fix errors
      run: sudo apt install libasound2-dev
      run: sudo apt install libasound2-dev
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
